"""Add fetched column to raw_listings

Revision ID: 9fbda9d11e0b
Revises: c7edd38f52da
Create Date: 2025-01-09 13:50:13.445908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbda9d11e0b'
down_revision: Union[str, None] = 'c7edd38f52da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_listings', sa.Column('fetched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_listings', 'fetched')
    # ### end Alembic commands ###
