"""Second migration

Revision ID: c7edd38f52da
Revises: 902706857e8e
Create Date: 2025-01-05 01:32:31.986128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7edd38f52da'
down_revision: Union[str, None] = '902706857e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_listings', sa.Column('combined_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_listings', 'combined_text')
    # ### end Alembic commands ###
